### ISSUE TITLE
"Skip if not a valid torrent URL" is bad user experience

### ISSUE THREAD

**Issue by yfdyh000** [hensm/utorrent_connector#2]
You should use the notification, an option, or describe it on Add-ons site.

**Comment by hensm** [comment]
Yeah, I was hoping to just not show it at all, but until [1280370](https://bugzilla.mozilla.org/show_bug.cgi?id=1280370) is fixed, a notification is probably the best solution.

**Comment by hensm** [comment]
54615cc adds a notification. Two extra strings to localize, though.
