### ISSUE TITLE
how to connect to µTorrent Server 3.3? (is it possible?)

### ISSUE THREAD

**Issue by snapsnapsnap** [hensm/utorrent_connector#5]
![image](https://user-images.githubusercontent.com/3761022/32910219-f4d5024e-cb08-11e7-9377-d6bae0cdfc18.png)

this is my µTorrent Server 3.3 running on my local network, as seen from my firefox on my laptop.

this is my setup
![image](https://user-images.githubusercontent.com/3761022/32910272-13b3f7c4-cb09-11e7-9503-0be2a335e3da.png)

and this is the error I get when I try to add a magnet link

![image](https://user-images.githubusercontent.com/3761022/32910294-24a1ce4e-cb09-11e7-9f5f-172282ee47f6.png)

it is possible that I have setup something wrong... any suggestions to what I can try next?

**Comment by hensm** [comment]
Ah, okay. So, the host isn't a URL, it's a hostname. You just want `10.0.0.10` in that field. I've yet to implement any useful error handling. I should probably validate those fields too.
