### ISSUE TITLE
Error trying to load torrents parser.parseFromString

### ISSUE THREAD

**Issue by StGabriel1** [hensm/utorrent_connector#6]
Gday

Having issues with adding magnet links to my utorrent running on a different machine on home network. 
![utorrent error](https://user-images.githubusercontent.com/33743206/32930394-64a95c90-cbc3-11e7-914a-b2b13dc238d3.JPG)

Any suggestions?

![utorrent error1](https://user-images.githubusercontent.com/33743206/32930442-9dda6608-cbc3-11e7-9e5f-906d05ee1dbc.JPG)

**Comment by hensm** [comment]
Probably the username/password is wrong. Double check they match the ones set in the uTorrent client preferences.

**Comment by StGabriel1** [comment]
Just double checked against saved passwords in Firefox for UI login , even tried an alternative (which should be incorrect) It gave the same error. So did as suggested, for some reason, the password was different, Issue now resolved as PEBKAC error. Much appreciated for your assistance @hensm
